export const skillsOptions = [
  { value: "javascript", label: "JavaScript" },
  { value: "react", label: "React.js" },
  { value: "angular", label: "Angular" },
  { value: "vuejs", label: "Vue.js" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "csharp", label: "C#" },
  { value: "php", label: "PHP" },
  { value: "ruby", label: "Ruby" },
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "typescript", label: "TypeScript" },
  { value: "sql", label: "SQL" },
  { value: "nodejs", label: "Node.js" },
  { value: "expressjs", label: "Express.js" },
  { value: "mongodb", label: "MongoDB" },
  { value: "mysql", label: "MySQL" },
  { value: "git", label: "Git" },
  { value: "agile", label: "Agile" },
  { value: "scrum", label: "Scrum" },
  { value: "devops", label: "DevOps" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "aws", label: "Amazon Web Services (AWS)" },
  { value: "azure", label: "Microsoft Azure" },
  { value: "gcp", label: "Google Cloud Platform (GCP)" },
  { value: "restapi", label: "RESTful API Design" },
  { value: "graphql", label: "GraphQL" },
  { value: "redux", label: "Redux" },
  { value: "webpack", label: "Webpack" },
  { value: "sass", label: "Sass" },
  { value: "responsive-design", label: "Responsive Web Design" },
  { value: "testing", label: "Automated Testing" },
  { value: "continuousintegration", label: "Continuous Integration (CI/CD)" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "machinelearning", label: "Machine Learning" },
  { value: "datascience", label: "Data Science" },
  { value: "uxui", label: "UI/UX Design" },
  { value: "agiledevelopment", label: "Agile Development" },
  { value: "productmanagement", label: "Product Management" },
  { value: "teamcollaboration", label: "Team Collaboration" },
  { value: "problem-solving", label: "Problem Solving" },
  { value: "communication", label: "Communication" },
  { value: "creativity", label: "Creativity" },
  { value: "laravel", label: "Laravel" },
  { value: "symfony", label: "Symfony" },
  { value: "flask", label: "Flask" },
  { value: "spring", label: "Spring Framework" },
  { value: "django", label: "Django" },
  { value: "rubyonrails", label: "Ruby on Rails" },
  { value: "androiddev", label: "Android App Development" },
  { value: "iosdev", label: "iOS App Development" },
  { value: "reactnative", label: "React Native" },
  { value: "flutter", label: "Flutter" },
  { value: "kotlin", label: "Kotlin" },
  { value: "swift", label: "Swift" },
  { value: "unity", label: "Unity" },
  { value: "unreal", label: "Unreal Engine" },
  { value: "gamedev", label: "Game Development" },
  { value: "tensorflow", label: "TensorFlow" },
  { value: "pytorch", label: "PyTorch" },
  { value: "nlp", label: "Natural Language Processing (NLP)" },
  { value: "computer vision", label: "Computer Vision" },
  { value: "bigdata", label: "Big Data" },
  { value: "hadoop", label: "Hadoop" },
  { value: "spark", label: "Apache Spark" },
  { value: "blockchain", label: "Blockchain" },
  { value: "solidity", label: "Solidity" },
  { value: "ethereum", label: "Ethereum" },
  { value: "smartcontracts", label: "Smart Contracts" },
  { value: "frontend", label: "Frontend Development" },
  { value: "backend", label: "Backend Development" },
  { value: "fullstack", label: "Full Stack Development" },
  { value: "mobiledev", label: "Mobile App Development" },
  { value: "cloudcomputing", label: "Cloud Computing" },
  { value: "azuredevops", label: "Azure DevOps" },
  { value: "jenkins", label: "Jenkins" },
  { value: "gitlabci", label: "GitLab CI/CD" },
  { value: "bitbucketpipelines", label: "Bitbucket Pipelines" },
  { value: "terraform", label: "Terraform" },
  { value: "ansible", label: "Ansible" },
  { value: "chef", label: "Chef" },
  { value: "puppet", label: "Puppet" },
  { value: "bashscripting", label: "Bash Scripting" },
  { value: "linux", label: "Linux" },
  { value: "windows", label: "Windows" },
  { value: "networking", label: "Networking" },
  { value: "databases", label: "Databases" },
  { value: "nosql", label: "NoSQL Databases" },
  { value: "restfulapi", label: "RESTful API" },
  { value: "microservices", label: "Microservices" },
  { value: "serverless", label: "Serverless" },
  { value: "scalability", label: "Scalability" },
  { value: "performanceoptimization", label: "Performance Optimization" },
  { value: "usability", label: "Usability" },
  { value: "accessibility", label: "Accessibility" },
  { value: "internationalization", label: "Internationalization" },
  { value: "multithreading", label: "Multithreading" },
  { value: "datastructures", label: "Data Structures" },
  { value: "algorithms", label: "Algorithms" },
  { value: "problem-solving", label: "Problem Solving" },
  { value: "gitflow", label: "Git Flow" },
  { value: "continuousintegration", label: "Continuous Integration" },
  { value: "agile", label: "Agile Methodologies" },
  { value: "leadership", label: "Leadership" },
  { value: "teamwork", label: "Teamwork" },
  { value: "communication", label: "Effective Communication" },
  { value: "time management", label: "Time Management" },
  { value: "mentoring", label: "Mentoring" },
  { value: "problem-solving", label: "Problem Solving" },
  { value: "adaptability", label: "Adaptability" },
  { value: "empathy", label: "Empathy" },
  { value: "creativity", label: "Creativity" },
  { value: "innovation", label: "Innovation" },
];
